apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: k8s-todo-app
  namespace: argocd

spec:
  project: todoapp
  source:
    repoURL: 'https://github.com/uuthman/todo-app-laravel-devops'
    path: helm/todo-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - ./values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
