apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: todoapp
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  sourceRepos:
    - "https://github.com/uuthman/todo-app-laravel-devops"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
      name: "*"

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  # By default, apps may sync to any cluster specified under the `destinations` field, even if they are not
  # scoped to this project. Set the following field to `true` to restrict apps in this cluster to only clusters
  # scoped to this project.
  permitOnlyProjectScopedClusters: false
