apiVersion: v1
kind: Service
metadata:
  name: todo-postgres
spec:
  selector:
    tier: backend
    layer: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort

