apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -w 2 -z todo-postgres 5432; do echo waiting for db; sleep 2; done;']
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: todo-postgres
                  key: username
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          envFrom:
            - secretRef:
                name: todo-secret
#          livenessProbe:
#            exec:
#              command:
#                - curl --fail http://127.0.0.1 || exit 1
#            failureThreshold: 5
#            periodSeconds: 30
#            timeoutSeconds: 10
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/.env
              name: todo-config
              subPath: .env
          workingDir: /app
      volumes:
        - configMap:
            items:
              - key: .env
                path: .env
            name: todo-config
          name: todo-config
