apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: app-svc
spec:
  selector:
    app: todo-app
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30007
