apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
stringData:
  APP_KEY: "base64:48/cVoLrp6HPNgVK6AA2zMmstMDG4Z/GnWp23KPamAg="
  DB_USERNAME: "tododb-user"
  DB_PASSWORD: "Gi6J6WPGnjQpuuzUbv47"
