name: Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'README.md'
      - 'docker-compose.yaml'


jobs:
  Checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4



  Push-to-docker:
    runs-on: ubuntu-latest


    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{github.run_id}}


  Update-new-tag-in-helm:
    runs-on: ubuntu-latest

    needs: Push-to-docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: '${{ github.token }}'

      - name: Update tag in Helm chart
        run: |
            sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/todo-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "uthmanayinde6@gmail.com"
          git config --global user.name "uuthman"
          git add helm/todo-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
